USE [Car_Dev01]

go

INSERT INTO [dbo].[vehiclecategory]
            ([name],
             [isactive])
VALUES      ('Car',
             1),
            ('Van',
             1),
            ('SUV / Jeep',
             1),
            ('Motorcycle',
             1),
            ('Crew Cab',
             1),
            ('Pickup/ Double Cab',
             1),
            ('Bus',
             1),
            ('Lorry/ Tipper',
             1),
            ('Three Wheel',
             1),
            ('Other',
             1),
            ('Tractor',
             1),
            ('Heavy-Duty',
             1),
            ('Bicycle',
             1)

INSERT INTO [dbo].[vehiclecondition]
            ([name],
             [isactive])
VALUES      ('Antique',
             1),
            ('Brand New',
             1),
            ('Registered',
             1),
            ('Unregistered',
             1)

INSERT INTO [dbo].[transmission]
            ([name],
             [isactive])
VALUES      ('Automatic',
             1),
            ('Manual',
             1)

INSERT INTO [dbo].[vehiclecompany]
            ([name],
             [isactive])
VALUES      ('Acura',
             1),
            ('Alfa-Romeo',
             1),
            ('Ashok-Leyland',
             1),
            ('Aston',
             1),
            ('Atco',
             1),
            ('Audi',
             1),
            ('Austin',
             1),
            ('Bajaj',
             1),
            ('Bentley',
             1),
            ('BMW',
             1),
            ('Cadillac',
             1),
            ('Cal',
             1),
            ('CAT',
             1),
            ('Ceygra',
             1),
            ('Changan',
             1),
            ('Chery',
             1),
            ('Chevrolet',
             1),
            ('Chrysler',
             1),
            ('Citroen',
             1),
            ('Corvette',
             1),
            ('Daewoo',
             1),
            ('Daido',
             1),
            ('Daihatsu',
             1),
            ('Datsun',
             1),
            ('Demak',
             1),
            ('Dfac',
             1),
            ('DFSK',
             1),
            ('Ducati',
             1),
            ('Eicher',
             1),
            ('FAW',
             1),
            ('Ferrari',
             1),
            ('Fiat',
             1),
            ('Force',
             1),
            ('Ford',
             1),
            ('Foton',
             1),
            ('Hero',
             1),
            ('Hero-Honda',
             1),
            ('Higer',
             1),
            ('Hillman',
             1),
            ('HINO',
             1),
            ('Hitachi',
             1),
            ('Honda',
             1),
            ('Hummer',
             1),
            ('Hyundai',
             1),
            ('IHI',
             1),
            ('Isuzu',
             1),
            ('Iveco',
             1),
            ('JAC',
             1),
            ('Jaguar',
             1),
            ('JCB',
             1),
            ('Jeep',
             1),
            ('JiaLing',
             1),
            ('JMC',
             1),
            ('John-Deere',
             1),
            ('Jonway',
             1),
            ('KAPLA',
             1),
            ('Kawasaki',
             1),
            ('Kia',
             1),
            ('Kinetic',
             1),
            ('KMC',
             1),
            ('Kobelco',
             1),
            ('Komatsu',
             1),
            ('KTM',
             1),
            ('Kubota',
             1),
            ('Lamborghini',
             1),
            ('Land-Rover',
             1),
            ('Lexus',
             1),
            ('Loncin',
             1),
            ('Longjia',
             1),
            ('Lotus',
             1),
            ('Lti',
             1),
            ('Mahindra',
             1),
            ('Maserati',
             1),
            ('Massey-Ferguson',
             1),
            ('Mazda',
             1),
            ('Mercedes-Benz',
             1),
            ('Metrocab',
             1),
            ('MG',
             1),
            ('Mg-Rover',
             1),
            ('Micro',
             1),
            ('Mini',
             1),
            ('Minnelli',
             1),
            ('Mitsubishi',
             1),
            ('Morgan',
             1),
            ('Morris',
             1),
            ('New-Holland',
             1),
            ('Nissan',
             1),
            ('Opel',
             1),
            ('Other',
             1),
            ('Perodua',
             1),
            ('Peugeot',
             1),
            ('Piaggio',
             1),
            ('Porsche',
             1),
            ('Powertrac',
             1),
            ('Proton',
             1),
            ('Range-Rover',
             1),
            ('Ranomoto',
             1),
            ('Renault',
             1),
            ('Reva',
             1),
            ('Rolls-Royce',
             1),
            ('Saab',
             1),
            ('Sakai',
             1),
            ('Seat',
             1),
            ('Singer',
             1),
            ('Skoda',
             1),
            ('Smart',
             1),
            ('Sonalika',
             1),
            ('Subaru',
             1),
            ('Suzuki',
             1),
            ('Swaraj',
             1),
            ('Syuk',
             1),
            ('TAFE',
             1),
            ('Tata',
             1),
            ('Tesla',
             1),
            ('Toyota',
             1),
            ('Triumph',
             1),
            ('TVS',
             1),
            ('Vauxhall',
             1),
            ('Vespa',
             1),
            ('Volkswagen',
             1),
            ('Volvo',
             1),
            ('Wave',
             1),
            ('Willys',
             1),
            ('Yamaha',
             1),
            ('Yanmar',
             1),
            ('Yuejin',
             1),
            ('Zongshen',
             1),
            ('Zotye',
             1)

INSERT INTO manufacturedyear
            ([year],
             [isactive])
VALUES      ('Before 1948',
             1)

DECLARE @startnum INT=1948
DECLARE @endnum INT=2022;

WITH gen
     AS (SELECT @startnum AS num
         UNION ALL
         SELECT num + 1
         FROM   gen
         WHERE  num + 1 <= @endnum)
SELECT *
INTO   #tempnumbers
FROM   gen
OPTION (maxrecursion 10000)

INSERT INTO [dbo].[manufacturedyear]
            ([year],
             [isactive])
SELECT num,
       1
FROM   #tempnumbers

DROP TABLE #tempnumbers

SELECT *
FROM   manufacturedyear

go 